# Generated by Django 5.2.15 on 2026-09-18 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db", "0128_thm_workflow_rules"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_worklog_approval_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="project",
            name="worklog_approver_ids",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="worklog",
            name="review_note",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="worklog",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="worklog",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_worklogs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="worklog",
            name="status",
            field=models.CharField(
                choices=[
                    ("submitted", "Submitted"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="approved",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="worklog",
            index=models.Index(
                fields=["project", "status"], name="work_logs_project_ba6665_idx"
            ),
        ),
    ]
