# Generated by Django 5.2.15 on 2026-09-18 02:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("db", "0130_thm_project_templates"),
    ]

    operations = [
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                ("is_shared", models.BooleanField(default=True)),
                ("logo_props", models.JSONField(default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="thm_dashboards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thm_dashboards",
                        to="db.project",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thm_dashboards",
                        to="db.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard",
                "verbose_name_plural": "Dashboards",
                "db_table": "thm_dashboards",
                "ordering": ("name",),
            },
        ),
        migrations.CreateModel(
            name="DashboardWidget",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Last Modified At"),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Deleted At"),
                ),
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "chart_type",
                    models.CharField(
                        choices=[
                            ("number", "Number"),
                            ("bar", "Bar"),
                            ("pie", "Pie"),
                            ("line", "Line"),
                            ("table", "Table"),
                        ],
                        default="bar",
                        max_length=20,
                    ),
                ),
                (
                    "metric",
                    models.CharField(
                        choices=[
                            ("count", "Work item count"),
                            ("estimate_points", "Estimate points"),
                            ("worklog_hours", "Logged hours"),
                        ],
                        default="count",
                        max_length=30,
                    ),
                ),
                (
                    "group_by",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "None"),
                            ("state", "State"),
                            ("state_group", "State group"),
                            ("priority", "Priority"),
                            ("assignee", "Assignee"),
                            ("label", "Label"),
                            ("project", "Project"),
                            ("module", "Module"),
                            ("cycle", "Cycle"),
                            ("created_by", "Creator"),
                            ("created_month", "Month created"),
                            ("completed_month", "Month completed"),
                            ("target_month", "Month due"),
                        ],
                        default="",
                        max_length=30,
                    ),
                ),
                ("filters", models.JSONField(blank=True, default=dict)),
                ("width", models.PositiveSmallIntegerField(default=1)),
                ("height", models.PositiveSmallIntegerField(default=1)),
                ("sort_order", models.FloatField(default=65535)),
                ("config", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created By",
                    ),
                ),
                (
                    "dashboard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="db.dashboard",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated_by",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Last Modified By",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dashboard Widget",
                "verbose_name_plural": "Dashboard Widgets",
                "db_table": "thm_dashboard_widgets",
                "ordering": ("sort_order", "created_at"),
            },
        ),
    ]
